from PyQt5 import QtCore, QtGui, QtWidgets


class addEditCoffeeFormUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(293, 187)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.coffee_grade = QtWidgets.QLineEdit(self.centralwidget)
        self.coffee_grade.setGeometry(QtCore.QRect(150, 10, 131, 20))
        self.coffee_grade.setObjectName("coffee_grade")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.degree_of_roasting = QtWidgets.QComboBox(self.centralwidget)
        self.degree_of_roasting.setGeometry(QtCore.QRect(150, 30, 131, 22))
        self.degree_of_roasting.setObjectName("degree_of_roasting")
        self.ground_or_in_grains = QtWidgets.QComboBox(self.centralwidget)
        self.ground_or_in_grains.setGeometry(QtCore.QRect(150, 50, 131, 22))
        self.ground_or_in_grains.setObjectName("ground_or_in_grains")
        self.taste_description = QtWidgets.QLineEdit(self.centralwidget)
        self.taste_description.setGeometry(QtCore.QRect(150, 70, 131, 20))
        self.taste_description.setObjectName("taste_description")
        self.price = QtWidgets.QLineEdit(self.centralwidget)
        self.price.setGeometry(QtCore.QRect(150, 90, 131, 20))
        self.price.setObjectName("price")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.packing_volume = QtWidgets.QLineEdit(self.centralwidget)
        self.packing_volume.setGeometry(QtCore.QRect(150, 110, 131, 20))
        self.packing_volume.setObjectName("packing_volume")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.createButton = QtWidgets.QPushButton(self.centralwidget)
        self.createButton.setGeometry(QtCore.QRect(30, 140, 75, 23))
        self.createButton.setObjectName("createButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(180, 140, 75, 23))
        self.saveButton.setObjectName("saveButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.saveButton.hide()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Название сорта"))
        self.label_3.setText(_translate("MainWindow", "Молотый/В зёрнах"))
        self.label_4.setText(_translate("MainWindow", "Описание вкуса"))
        self.label_5.setText(_translate("MainWindow", "Степень обжарки"))
        self.label_6.setText(_translate("MainWindow", "Цена"))
        self.label_7.setText(_translate("MainWindow", "Объём упаковки"))
        self.createButton.setText(_translate("MainWindow", "Создать"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить"))
